#pragma once 






// ScanCode set 1 
int ScanCodeToKeyCode [0xD8];

/* key pressed scancode */ 
ScanCodeToKeyCode[0x01] = 4017;   // escape pressed
ScanCodeToKeyCode[0x02] = 4018;   // 1 pressed
ScanCodeToKeyCode[0x03] = 4019;   // 2 pressed
ScanCodeToKeyCode[0x04] = 4020;   // 3 pressed
ScanCodeToKeyCode[0x05] =""   // 4 pressed	
ScanCodeToKeyCode[0x06] =""   // 5 pressed
ScanCodeToKeyCode[0x07] =""   // 6 pressed
ScanCodeToKeyCode[0x08] =""   // 7 pressed
ScanCodeToKeyCode[0x09] =""   // 8 pressed	
ScanCodeToKeyCode[0x0A] =""   // 9 pressed	
ScanCodeToKeyCode[0x0B] =""   // 0 (zero) pressed
ScanCodeToKeyCode[0x0C] =""   // - pressed
ScanCodeToKeyCode[0x0D] =""   // = pressed	
ScanCodeToKeyCode[0x0E] =""   // backspace pressed
ScanCodeToKeyCode[0x0F] =""   // tab pressed
ScanCodeToKeyCode[0x10] =""  	// Q pressed
ScanCodeToKeyCode[0x11] =""   // W pressed	
ScanCodeToKeyCode[0x12] ="" 	// E pressed
ScanCodeToKeyCode[0x13] ="" 	// R pressed
ScanCodeToKeyCode[0x14] ="" 	// T pressed
ScanCodeToKeyCode[0x15] ="" 	// Y pressed	
ScanCodeToKeyCode[0x16] ="" 	// U pressed
ScanCodeToKeyCode[0x17] ="" 	// I pressed
ScanCodeToKeyCode[0x18] ="" 	// O pressed
ScanCodeToKeyCode[0x19] ="" 	// P pressed	
ScanCodeToKeyCode[0x1A] =""   // [ pressed
ScanCodeToKeyCode[0x1B] =""   // ] pressed
ScanCodeToKeyCode[0x1C] =""   // enter pressed
ScanCodeToKeyCode[0x1D] =""   // left control pressed
ScanCodeToKeyCode[0x1E] ="" 	// A pressed
ScanCodeToKeyCode[0x1F] ="" 	// S pressed
ScanCodeToKeyCode[0x20] ="" 	// D pressed
ScanCodeToKeyCode[0x21] ="" 	// F pressed
ScanCodeToKeyCode[0x22] ="" 	// G pressed
ScanCodeToKeyCode[0x23] ="" 	// H pressed
ScanCodeToKeyCode[0x24] ="" 	// J pressed
ScanCodeToKeyCode[0x25] ="" 	// K pressed
ScanCodeToKeyCode[0x26] ="" 	// L pressed
ScanCodeToKeyCode[0x27] =""   //  ; pressed
ScanCodeToKeyCode[0x28] =""   // ' (single quote) pressed
ScanCodeToKeyCode[0x29] =""   // ` (back tick) pressed
ScanCodeToKeyCode[0x2A] =""   // left shift pressed	
ScanCodeToKeyCode[0x2B] =""   // \ pressed
ScanCodeToKeyCode[0x2C] ="" 	// Z pressed
ScanCodeToKeyCode[0x2D] ="" 	// X pressed
ScanCodeToKeyCode[0x2E] ="" 	// C pressed	
ScanCodeToKeyCode[0x2F] ="" 	// V pressed
ScanCodeToKeyCode[0x30] ="" 	// B pressed
ScanCodeToKeyCode[0x31] ="" 	// N pressed
ScanCodeToKeyCode[0x32] ="" 	// M pressed
ScanCodeToKeyCode[0x33] =""   // , pressed
ScanCodeToKeyCode[0x34] =""   // . pressed
ScanCodeToKeyCode[0x35] =""   // / pressed
ScanCodeToKeyCode[0x36] =""   // right shift pressed
ScanCodeToKeyCode[0x37] =""   // (keypad) * pressed
ScanCodeToKeyCode[0x38] =""   // left alt pressed	
ScanCodeToKeyCode[0x39] =""   // space pressed	
ScanCodeToKeyCode[0x3A] =""   // CapsLock pressed
ScanCodeToKeyCode[0x3B] =""   // F1 pressed
ScanCodeToKeyCode[0x3C] =""   // F2 pressed
ScanCodeToKeyCode[0x3D] =""   // F3 pressed
ScanCodeToKeyCode[0x3E] ="" 	// F4 pressed
ScanCodeToKeyCode[0x3F] ="" 	// F5 pressed
ScanCodeToKeyCode[0x40] ="" 	// F6 pressed
ScanCodeToKeyCode[0x41] ="" 	// F7 pressed
ScanCodeToKeyCode[0x42] ="" 	// F8 pressed
ScanCodeToKeyCode[0x43] ="" 	// F9 pressed
ScanCodeToKeyCode[0x44] ="" 	// F10 pressed
ScanCodeToKeyCode[0x45] ="" 	// NumberLock pressed
ScanCodeToKeyCode[0x46] ="" 	// ScrollLock pressed
ScanCodeToKeyCode[0x47] ="" 	// (keypad) 7 pressed
ScanCodeToKeyCode[0x48] ="" 	// (keypad) 8 pressed
ScanCodeToKeyCode[0x49] ="" 	// (keypad) 9 pressed
ScanCodeToKeyCode[0x4A] ="" 	// (keypad) - pressed
ScanCodeToKeyCode[0x4B] ="" 	// (keypad) 4 pressed
ScanCodeToKeyCode[0x4C] ="" 	// (keypad) 5 pressed
ScanCodeToKeyCode[0x4D] ="" 	// (keypad) 6 pressed
ScanCodeToKeyCode[0x4E] ="" 	// (keypad) + pressed
ScanCodeToKeyCode[0x4F] ="" 	// (keypad) 1 pressed
ScanCodeToKeyCode[0x50] ="" 	// (keypad) 2 pressed
ScanCodeToKeyCode[0x51] ="" 	// (keypad) 3 pressed
ScanCodeToKeyCode[0x52] ="" 	// (keypad) 0 pressed
ScanCodeToKeyCode[0x53] ="" 	// (keypad) . pressed
ScanCodeToKeyCode[0x57] ="" 	// F11 pressed
ScanCodeToKeyCode[0x58] ="" 	// F12 pressed						


/* key released scanCode.""*/
ScanCodeToKeyCode[0x81] ="" 	// escape released
ScanCodeToKeyCode[0x82] ="" 	// 1 released
ScanCodeToKeyCode[0x83] ="" 	// 2 released
ScanCodeToKeyCode[0x84] ="" 	// 3 released
ScanCodeToKeyCode[0x85] ="" 	// 4 released
ScanCodeToKeyCode[0x86] ="" 	// 5 released
ScanCodeToKeyCode[0x87] ="" 	// 6 released
ScanCodeToKeyCode[0x88] ="" 	// 7 released
ScanCodeToKeyCode[0x89] ="" 	// 8 released
ScanCodeToKeyCode[0x8A] ="" 	// 9 released
ScanCodeToKeyCode[0x8B] ="" 	// 0 (zero) released
ScanCodeToKeyCode[0x8C] ="" 	// - released
ScanCodeToKeyCode[0x8D] ="" 	// = released
ScanCodeToKeyCode[0x8E] ="" 	// backspace released
ScanCodeToKeyCode[0x8F] ="" 	// tab released
ScanCodeToKeyCode[0x90] ="" 	// Q released
ScanCodeToKeyCode[0x91] ="" 	// W released
ScanCodeToKeyCode[0x92] ="" 	// E released
ScanCodeToKeyCode[0x93] ="" 	// R released
ScanCodeToKeyCode[0x94] ="" 	// T released
ScanCodeToKeyCode[0x95] ="" 	// Y released	
ScanCodeToKeyCode[0x96] ="" 	// U released
ScanCodeToKeyCode[0x97] ="" 	// I released
ScanCodeToKeyCode[0x98] ="" 	// O released	
ScanCodeToKeyCode[0x99] ="" 	// P released
ScanCodeToKeyCode[0x9A] ="" 	// [ released	
ScanCodeToKeyCode[0x9B] ="" 	// ] released
ScanCodeToKeyCode[0x9C] ="" 	// enter released
ScanCodeToKeyCode[0x9D] ="" 	// left control released
ScanCodeToKeyCode[0x9E] ="" 	// A released
ScanCodeToKeyCode[0x9F] ="" 	// S released
ScanCodeToKeyCode[0xA0] ="" 	// D released
ScanCodeToKeyCode[0xA1] ="" 	// F released
ScanCodeToKeyCode[0xA2] ="" 	// G released
ScanCodeToKeyCode[0xA3] ="" 	// H released
ScanCodeToKeyCode[0xA4] ="" 	// J released
ScanCodeToKeyCode[0xA5] ="" 	// K released
ScanCodeToKeyCode[0xA6] ="" 	// L released
ScanCodeToKeyCode[0xA7] ="" 	//  ; released
ScanCodeToKeyCode[0xA8] ="" 	// ' (single quote) released
ScanCodeToKeyCode[0xA9] ="" 	// ` (back tick) released
ScanCodeToKeyCode[0xAA] ="" 	// left shift released
ScanCodeToKeyCode[0xAB] ="" 	// \ released
ScanCodeToKeyCode[0xAC] ="" 	// Z released	
ScanCodeToKeyCode[0xAD] ="" 	// X released	
ScanCodeToKeyCode[0xAE] ="" 	// C released	
ScanCodeToKeyCode[0xAF] ="" 	// V released
ScanCodeToKeyCode[0xB0] ="" 	// B released	
ScanCodeToKeyCode[0xB1] ="" 	// N released	
ScanCodeToKeyCode[0xB2] ="" 	// M released	
ScanCodeToKeyCode[0xB3] ="" 	// , released
ScanCodeToKeyCode[0xB4] ="" 	// . released	
ScanCodeToKeyCode[0xB5] ="" 	// / released	
ScanCodeToKeyCode[0xB6] ="" 	// right shift released
ScanCodeToKeyCode[0xB7] ="" 	// (keypad) * released
ScanCodeToKeyCode[0xB8] ="" 	// left alt released	
ScanCodeToKeyCode[0xB9] ="" 	// space released	
ScanCodeToKeyCode[0xBA] ="" 	// CapsLock released	
ScanCodeToKeyCode[0xBB] ="" 	// F1 released
ScanCodeToKeyCode[0xBC] ="" 	// F2 released	
ScanCodeToKeyCode[0xBD] ="" 	// F3 released	
ScanCodeToKeyCode[0xBE] ="" 	// F4 released	
ScanCodeToKeyCode[0xBF] ="" 	// F5 released
ScanCodeToKeyCode[0xC0] ="" 	// F6 released	
ScanCodeToKeyCode[0xC1] ="" 	// F7 released	
ScanCodeToKeyCode[0xC2] ="" 	// F8 released	
ScanCodeToKeyCode[0xC3] ="" 	// F9 released
ScanCodeToKeyCode[0xC4] ="" 	// F10 released
ScanCodeToKeyCode[0xC5] ="" 	// NumberLock released
ScanCodeToKeyCode[0xC6] ="" 	// ScrollLock released
ScanCodeToKeyCode[0xC7] ="" 	// (keypad) 7 released
ScanCodeToKeyCode[0xC8] ="" 	// (keypad) 8 released	
ScanCodeToKeyCode[0xC9] ="" 	// (keypad) 9 released	
ScanCodeToKeyCode[0xCA] ="" 	// (keypad) - released	
ScanCodeToKeyCode[0xCB] ="" 	// (keypad) 4 released
ScanCodeToKeyCode[0xCC] ="" 	// (keypad) 5 released	
ScanCodeToKeyCode[0xCD] ="" 	// (keypad) 6 released	
ScanCodeToKeyCode[0xCE] ="" 	// (keypad) + released	
ScanCodeToKeyCode[0xCF] ="" 	// (keypad) 1 released
ScanCodeToKeyCode[0xD0] ="" 	// (keypad) 2 released	
ScanCodeToKeyCode[0xD1] ="" 	// (keypad) 3 released	
ScanCodeToKeyCode[0xD2] ="" 	// (keypad) 0 released	
ScanCodeToKeyCode[0xD3] ="" 	// (keypad) . released
ScanCodeToKeyCode[0xD7] ="" 	// F11 released
ScanCodeToKeyCode[0xD8] ="" 	// F12 released					